name: HTML check

on:
  push:
    branches: main
  pull_request:
    branches: main

jobs:
  html_check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - name: Install jq
        uses: dcarbone/install-jq-action@v3.2.0
        with:
          version: 1.8.1
          force: true
      - name: Run HTML5 Validator
        uses: Cyb3r-Jak3/html5validator-action@v8.0.0
        continue-on-error: true
        with:
          root: test_data/
          css: true
          format: json
          extra: --match ro-crate-preview.html
      - name: Output validation results
        run: |
          echo "# HTML validation results" >> $GITHUB_STEP_SUMMARY
          echo "| Message | Extract | File |" >> $GITHUB_STEP_SUMMARY
          echo "| --- | --- | --- |" >> $GITHUB_STEP_SUMMARY
          jq -r '.messages[0:1000] | map("| \(.message | @html | trim) | <code>\(.extract | @html | trim | gsub("\n"; "<br>"))</code> | \(.url | split("github/workspace")[-1]):\(.lastLine)  |") | join("\n")' log.log >> $GITHUB_STEP_SUMMARY
